become_override: false
ocp_username: opentlc-mgr
silent: false

# ------------------------------------------------
# App Services Lab Deployment
# ------------------------------------------------
lab_setup: true

# Shared Users
user_count: 1
user_prefix: user

# ------------------------------------------------
# Service Binding Operator
# ------------------------------------------------

service_binding_operator_name: rh-service-binding-operator
service_binding_operator_namespace: openshift-operators
service_binding_operator_catalog: redhat-operators
service_binding_operator_channel: stable
service_binding_operator_automatic_install_plan_approval: true
service_binding_operator_starting_csv: ""
service_binding_operator_csv_nameprefix: service-binding-operator
service_binding_operator_use_catalog_snapshot: true
service_binding_operator_catalogsource_name: redhat-operators-snapshot-service-binding
service_binding_operator_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
service_binding_operator_catalog_snapshot_image_tag: "v4.13_2023_06_26"

# ------------------------------------------------
# AMQ Streams Operator
# ------------------------------------------------

amq_streams_operator_channel: ""
amq_streams_operator_automatic_install_plan_approval: true
amq_streams_operator_starting_csv: ""
amq_streams_operator_name: amq-streams
amq_streams_operator_namespace: openshift-operators
amq_streams_operator_catalog: redhat-operators
amq_streams_operator_csv_prefix: amqstreams
amq_streams_operator_wait_for_deploy: true
amq_streams_operator_use_catalog_snapshot: true
amq_streams_operator_catalogsource_name: redhat-operators-snapshot-amq-streams
amq_streams_operator_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
amq_streams_operator_catalog_snapshot_image_tag: "v4.13_2023_06_26"
amq_streams_operator_requests_memory: 768Mi
amq_streams_operator_limits_memory: 768Mi


# ------------------------------------------------
# App services
# ------------------------------------------------

# Namespace
namespace_prefix: globex-

app_services_application_name: globex-app-user
app_services_application_namespace: openshift-gitops

app_services_application_repo: https://github.com/rh-mad-app-services/mad-app-services-helm.git
app_services_application_repo_tag: main
app_services_application_repo_path: globex

# Inventory app
inventory_db_image: quay.io/globex-recommendation/inventory-database:app-mod-workshop
inventory_service_image: quay.io/globex-recommendation/inventory:app-mod-workshop

# Catalog app
catalog_db_image: quay.io/globex-recommendation/catalog-database:app-mod-workshop
catalog_service_image: quay.io/globex-recommendation/catalog:app-mod-workshop

# Globex UI app
globex_ui_image: quay.io/globex-recommendation/globex-recommendation-ui:app-mod-workshop

# Activity Tracking app
activity_tracking_service_image: quay.io/globex-recommendation/activity-tracking-service:app-mod-workshop

# Recommendation Engine app
recommendation_engine_image: quay.io/globex-recommendation/recommendation-engine:app-mod-workshop

# Activity Tracking Simulator
activity_tracking_simulator_image: >-
  quay.io/globex-recommendation/activity-tracking-simulator:app-mod-workshop

# Order Placement app
order_placement_service_image: quay.io/globex-recommendation/order-placement-service:app-mod-workshop


# ------------------------------------------------
# Kafka
# ------------------------------------------------
kafka_enabled: true

kafka_replicas: 2

kafka_security_protocol: SASL_PLAINTEXT
kafka_sasl_mechanism: SCRAM-SHA-512
kafka_client_id: globex
kafka_client_secret: globex


# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

openshift_gitops_channel: latest
openshift_gitops_automatic_install_plan_approval: true
openshift_gitops_starting_csv: ""
openshift_gitops_pipelines_csv_prefix: openshift-pipelines-operator-rh

openshift_gitops_setup_cluster_admin: true

openshift_gitops_update_route_tls: true

openshift_gitops_update_resources: true

# ApplicationSet Controller
openshift_gitops_applicationset_controller_update: false
openshift_gitops_applicationset_controller_requests_cpu: 250m
openshift_gitops_applicationset_controller_requests_memory: 512Mi
openshift_gitops_applicationset_controller_limits_cpu: "2"
openshift_gitops_applicationset_controller_limits_memory: 1Gi

# Application Controller
openshift_gitops_controller_update: true
openshift_gitops_controller_requests_cpu: "2"
openshift_gitops_controller_requests_memory: 4Gi
openshift_gitops_controller_limits_cpu: "4"
openshift_gitops_controller_limits_memory: 4Gi
# Setting a default value for reconcile timeout as it needs to be configurable
# Reduce this value if you want to sync more frequently
openshift_gitops_controller_app_sync: 3m

openshift_gitops_controller_remove_memory_limits: true

# Redis
openshift_gitops_redis_update: false
openshift_gitops_redis_requests_cpu: 250m
openshift_gitops_redis_requests_memory: 128Mi
openshift_gitops_redis_limits_cpu: 500m
openshift_gitops_redis_limits_memory: 256Mi

# Repo Server
openshift_gitops_repo_update: true
openshift_gitops_repo_requests_cpu: 500m
openshift_gitops_repo_requests_memory: 512Mi
openshift_gitops_repo_limits_cpu: "2"
openshift_gitops_repo_limits_memory: 2Gi

# DEX
openshift_gitops_dex_update: false
openshift_gitops_dex_requests_cpu: 125m
openshift_gitops_dex_requests_memory: 128Mi
openshift_gitops_dex_limits_cpu: 500m
openshift_gitops_dex_limits_memory: 256Mi

# Server
openshift_gitops_server_update: false
openshift_gitops_server_requests_cpu: 250m
openshift_gitops_server_requests_memory: 128Mi
openshift_gitops_server_limits_cpu: 500m
openshift_gitops_server_limits_memory: 256Mi

openshift_gitops_resource_customizations: |
  operators.coreos.com/Subscription:
    health.lua: |
      health_status = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          numDegraded = 0
          numPending = 0
          msg = ""
          for i, condition in pairs(obj.status.conditions) do
            msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
            if condition.type == "InstallPlanPending" and condition.status == "True" then
              numPending = numPending + 1
            elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
              numDegraded = numDegraded + 1
            elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed") and condition.status == "True" then
              numDegraded = numDegraded + 1
            end
          end
          if numDegraded == 0 and numPending == 0 then
            health_status.status = "Healthy"
            health_status.message = msg
            return health_status
          elseif numPending > 0 and numDegraded == 0 then
            health_status.status = "Progressing"
            health_status.message = "An install plan for a subscription is pending installation"
            return health_status
          else
            health_status.status = "Degraded"
            health_status.message = msg
            return health_status
          end
        end
      end
      health_status.status = "Progressing"
      health_status.message = "An install plan for a subscription is pending installation"
      return health_status

# e.g.
# openshift_gitops_resource_customizations: |
  # argoproj.io/Application:
  #   health.lua: |
  #     hs = {}
  #     hs.status = "Progressing"
  #     hs.message = ""
  #     if obj.status ~= nil then
  #       if obj.status.health ~= nil then
  #         hs.status = obj.status.health.status
  #         hs.message = obj.status.health.message
  #       end
  #     end
  #     return hs
# --------------------------------
# Operator Catalog Snapshot Settings
# --------------------------------
# See https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc
# for instructions on how to set up catalog snapshot images

openshift_gitops_use_catalog_snapshot: false
openshift_gitops_catalogsource_name: redhat-operators-snapshot-gitops
openshift_gitops_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
openshift_gitops_catalog_snapshot_image_tag: v4.10_2022_07_18